on:
  push:
    branches:
      - develop
env:
  DATABASE_URL: ${secrets.DATABASE_URL}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build Fat Jar
        run: ./gradlew fatjar
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: orthanc-kt-jar
          path: ./build/libs/orthanc-kt-*-all.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download file
        uses: actions/download-artifact@v4
        with:
          name: orthanc-kt-jar
          path: ./build/libs/orthanc-kt-*-all.jar
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Copy Image
        run: sshpass -v -p ${{ secrets.RPGPT_PASSWORD }} scp -o StrictHostKeyChecking=no compose/orthanc/docker-compose.yml Dockerfile orthanc-kt-*-all.jar root@${{ secrets.RPGPT_IP }}:~/orthanc
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPGPT_IP }}
          username: docker-user
          password: ${{ secrets.RPGPT_PASSWORD }}
          script: |
            cd ~/orthanc
            docker-compose down
            docker compose --env-file .env -p orthanc up -d
