on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build Fat Jar
        run: ./gradlew fatjar
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Copy Dockerfile
        run: sshpass -v -p ${{ secrets.RPGPT_PASSWORD }} scp -o StrictHostKeyChecking=no ./Dockerfile ${{ secrets.RPGPT_USER }}@${{ secrets.RPGPT_IP }}:~/orthanc
      - name: Copy compose
        run: sshpass -v -p ${{ secrets.RPGPT_PASSWORD }} scp -o StrictHostKeyChecking=no ./compose/orthanc/compose.yaml ${{ secrets.RPGPT_USER }}@${{ secrets.RPGPT_IP }}:~/orthanc/compose/orthanc
      - name: Copy Jar
        run: sshpass -v -p ${{ secrets.RPGPT_PASSWORD }} scp -o StrictHostKeyChecking=no ./build/libs/orthanc-kt-*-all.jar ${{ secrets.RPGPT_USER }}@${{ secrets.RPGPT_IP }}:~/orthanc
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPGPT_IP }}
          username: docker-user
          password: ${{ secrets.RPGPT_PASSWORD }}
          script: |
            cd ./orthanc
            docker compose -f ./compose/orthanc/compose.yaml --env-file production.env down
            docker compose -f ./compose/orthanc/compose.yaml --env-file production.env -p orthanc up -d
